<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: snow.proto

namespace GPBMetadata;

class Snow
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad0020a0a736e6f772e70726f746f1209736e6f77666c616b6522200a0b" .
            "4e6578745265717565737412110a09736572766963654964180120012803" .
            "22170a094e6578745265706c79120a0a026964180120012803221a0a0c50" .
            "6172736552657175657374120a0a026964180120012803224f0a0a506172" .
            "73655265706c7912110a0974696d657374616d70180120012803120e0a06" .
            "6e6f6465496418022001280312110a097365727669636549641803200128" .
            "03120b0a03736571180420012803327e0a09536e6f77666c616b6512360a" .
            "044e65787412162e736e6f77666c616b652e4e657874526571756573741a" .
            "142e736e6f77666c616b652e4e6578745265706c79220012390a05506172" .
            "736512172e736e6f77666c616b652e5061727365526571756573741a152e" .
            "736e6f77666c616b652e50617273655265706c79220042075a0570726f74" .
            "6f620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

