<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: snow.proto

namespace GPBMetadata;

class Snow
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9e020a0a736e6f772e70726f746f1209736e6f77666c616b6522200a0b" .
            "4e6578745265717565737412110a09736572766963654964180120012803" .
            "22170a094e6578745265706c79120a0a02696418012001280322190a0953" .
            "747265616d526571120c0a046e616d65180120012809221d0a0a53747265" .
            "616d52657370120f0a076d657373616765180120012809327f0a09536e6f" .
            "77666c616b6512360a044e65787412162e736e6f77666c616b652e4e6578" .
            "74526571756573741a142e736e6f77666c616b652e4e6578745265706c79" .
            "2200123a0a0548656c6c6f12142e736e6f77666c616b652e53747265616d" .
            "5265711a152e736e6f77666c616b652e53747265616d5265737022002801" .
            "300142075a0570726f746f620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

