<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: snow.proto

namespace GPBMetadata;

class Snow
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa8010a0a736e6f772e70726f746f1209736e6f77666c616b6522200a0b" .
            "4e6578745265717565737412110a09736572766963654964180120012803" .
            "22170a094e6578745265706c79120a0a02696418012001280332430a0953" .
            "6e6f77666c616b6512360a044e65787412162e736e6f77666c616b652e4e" .
            "657874526571756573741a142e736e6f77666c616b652e4e657874526570" .
            "6c79220042075a0570726f746f620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

