<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: snow.proto

namespace Snowflake;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>snowflake.NextRequest</code>
 */
class NextRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * service id
     *
     * Generated from protobuf field <code>int64 serviceId = 1;</code>
     */
    private $serviceId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $serviceId
     *           service id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Snow::initOnce();
        parent::__construct($data);
    }

    /**
     * service id
     *
     * Generated from protobuf field <code>int64 serviceId = 1;</code>
     * @return int|string
     */
    public function getServiceId()
    {
        return $this->serviceId;
    }

    /**
     * service id
     *
     * Generated from protobuf field <code>int64 serviceId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setServiceId($var)
    {
        GPBUtil::checkInt64($var);
        $this->serviceId = $var;

        return $this;
    }

}

