// Code generated by protoc-gen-go. DO NOT EDIT.
// source: snow.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NextRequest struct {
	ServiceId            int64    `protobuf:"varint,1,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NextRequest) Reset()         { *m = NextRequest{} }
func (m *NextRequest) String() string { return proto.CompactTextString(m) }
func (*NextRequest) ProtoMessage()    {}
func (*NextRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cdb8d9edcdba34d, []int{0}
}

func (m *NextRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NextRequest.Unmarshal(m, b)
}
func (m *NextRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NextRequest.Marshal(b, m, deterministic)
}
func (m *NextRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NextRequest.Merge(m, src)
}
func (m *NextRequest) XXX_Size() int {
	return xxx_messageInfo_NextRequest.Size(m)
}
func (m *NextRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NextRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NextRequest proto.InternalMessageInfo

func (m *NextRequest) GetServiceId() int64 {
	if m != nil {
		return m.ServiceId
	}
	return 0
}

type NextReply struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NextReply) Reset()         { *m = NextReply{} }
func (m *NextReply) String() string { return proto.CompactTextString(m) }
func (*NextReply) ProtoMessage()    {}
func (*NextReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cdb8d9edcdba34d, []int{1}
}

func (m *NextReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NextReply.Unmarshal(m, b)
}
func (m *NextReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NextReply.Marshal(b, m, deterministic)
}
func (m *NextReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NextReply.Merge(m, src)
}
func (m *NextReply) XXX_Size() int {
	return xxx_messageInfo_NextReply.Size(m)
}
func (m *NextReply) XXX_DiscardUnknown() {
	xxx_messageInfo_NextReply.DiscardUnknown(m)
}

var xxx_messageInfo_NextReply proto.InternalMessageInfo

func (m *NextReply) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type StreamReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamReq) Reset()         { *m = StreamReq{} }
func (m *StreamReq) String() string { return proto.CompactTextString(m) }
func (*StreamReq) ProtoMessage()    {}
func (*StreamReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cdb8d9edcdba34d, []int{2}
}

func (m *StreamReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamReq.Unmarshal(m, b)
}
func (m *StreamReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamReq.Marshal(b, m, deterministic)
}
func (m *StreamReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamReq.Merge(m, src)
}
func (m *StreamReq) XXX_Size() int {
	return xxx_messageInfo_StreamReq.Size(m)
}
func (m *StreamReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamReq.DiscardUnknown(m)
}

var xxx_messageInfo_StreamReq proto.InternalMessageInfo

func (m *StreamReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type StreamResp struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamResp) Reset()         { *m = StreamResp{} }
func (m *StreamResp) String() string { return proto.CompactTextString(m) }
func (*StreamResp) ProtoMessage()    {}
func (*StreamResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cdb8d9edcdba34d, []int{3}
}

func (m *StreamResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamResp.Unmarshal(m, b)
}
func (m *StreamResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamResp.Marshal(b, m, deterministic)
}
func (m *StreamResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamResp.Merge(m, src)
}
func (m *StreamResp) XXX_Size() int {
	return xxx_messageInfo_StreamResp.Size(m)
}
func (m *StreamResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamResp.DiscardUnknown(m)
}

var xxx_messageInfo_StreamResp proto.InternalMessageInfo

func (m *StreamResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type TestReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestReq) Reset()         { *m = TestReq{} }
func (m *TestReq) String() string { return proto.CompactTextString(m) }
func (*TestReq) ProtoMessage()    {}
func (*TestReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cdb8d9edcdba34d, []int{4}
}

func (m *TestReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestReq.Unmarshal(m, b)
}
func (m *TestReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestReq.Marshal(b, m, deterministic)
}
func (m *TestReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestReq.Merge(m, src)
}
func (m *TestReq) XXX_Size() int {
	return xxx_messageInfo_TestReq.Size(m)
}
func (m *TestReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TestReq.DiscardUnknown(m)
}

var xxx_messageInfo_TestReq proto.InternalMessageInfo

func (m *TestReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type TestRes struct {
	Res                  int64    `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestRes) Reset()         { *m = TestRes{} }
func (m *TestRes) String() string { return proto.CompactTextString(m) }
func (*TestRes) ProtoMessage()    {}
func (*TestRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cdb8d9edcdba34d, []int{5}
}

func (m *TestRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestRes.Unmarshal(m, b)
}
func (m *TestRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestRes.Marshal(b, m, deterministic)
}
func (m *TestRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestRes.Merge(m, src)
}
func (m *TestRes) XXX_Size() int {
	return xxx_messageInfo_TestRes.Size(m)
}
func (m *TestRes) XXX_DiscardUnknown() {
	xxx_messageInfo_TestRes.DiscardUnknown(m)
}

var xxx_messageInfo_TestRes proto.InternalMessageInfo

func (m *TestRes) GetRes() int64 {
	if m != nil {
		return m.Res
	}
	return 0
}

func init() {
	proto.RegisterType((*NextRequest)(nil), "snowflake.NextRequest")
	proto.RegisterType((*NextReply)(nil), "snowflake.NextReply")
	proto.RegisterType((*StreamReq)(nil), "snowflake.StreamReq")
	proto.RegisterType((*StreamResp)(nil), "snowflake.StreamResp")
	proto.RegisterType((*TestReq)(nil), "snowflake.TestReq")
	proto.RegisterType((*TestRes)(nil), "snowflake.TestRes")
}

func init() { proto.RegisterFile("snow.proto", fileDescriptor_4cdb8d9edcdba34d) }

var fileDescriptor_4cdb8d9edcdba34d = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x14, 0xc4, 0x9b, 0x36, 0x35, 0xec, 0x08, 0x22, 0x0f, 0x95, 0x9a, 0x0a, 0xca, 0x1e, 0xa4, 0x20,
	0x04, 0x51, 0xf1, 0xe0, 0xd1, 0x93, 0x5e, 0x3c, 0xa4, 0x9e, 0xbc, 0x45, 0xfb, 0x94, 0xe0, 0xa6,
	0xd9, 0xe6, 0xc5, 0x3f, 0xfd, 0x60, 0x7e, 0x3f, 0xd9, 0xb4, 0x5b, 0x03, 0xf1, 0x94, 0xc9, 0xcc,
	0x6f, 0xd9, 0x19, 0x16, 0x90, 0x79, 0xf9, 0x95, 0xd8, 0xaa, 0xac, 0x4b, 0x52, 0x4e, 0xbf, 0x9a,
	0xec, 0x9d, 0xf5, 0x19, 0xb6, 0x1f, 0xf8, 0xbb, 0x4e, 0x79, 0xf1, 0xc1, 0x52, 0xd3, 0x11, 0x94,
	0x70, 0xf5, 0x99, 0xbf, 0xf0, 0xfd, 0x6c, 0x14, 0x9c, 0x04, 0x93, 0x41, 0xfa, 0x67, 0xe8, 0x31,
	0xd4, 0x0a, 0xb6, 0x66, 0x49, 0x3b, 0xe8, 0xe7, 0x9e, 0xe9, 0xe7, 0x33, 0x7d, 0x0c, 0x35, 0xad,
	0x2b, 0xce, 0x8a, 0x94, 0x17, 0x44, 0x08, 0xe7, 0x59, 0xc1, 0x4d, 0xac, 0xd2, 0x46, 0xeb, 0x53,
	0xc0, 0x03, 0x62, 0x69, 0x84, 0xa8, 0x60, 0x91, 0xec, 0xcd, 0x43, 0xfe, 0x57, 0x1f, 0x22, 0x7a,
	0x64, 0x71, 0x95, 0x3a, 0x77, 0x8c, 0x7d, 0x24, 0xb4, 0x8b, 0x41, 0xc5, 0xb2, 0xce, 0x9c, 0xbc,
	0xf8, 0x09, 0xa0, 0xa6, 0x7e, 0x18, 0x5d, 0x23, 0x74, 0x5d, 0xe9, 0x20, 0xd9, 0x8c, 0x4d, 0x5a,
	0x4b, 0xe3, 0xbd, 0x8e, 0x6f, 0xcd, 0x52, 0xf7, 0xe8, 0x06, 0xc3, 0x3b, 0x36, 0xa6, 0xa4, 0x36,
	0xb0, 0x19, 0x16, 0xef, 0xff, 0xe3, 0x8a, 0xd5, 0xbd, 0x49, 0x70, 0x1e, 0xd0, 0x15, 0x42, 0x57,
	0x8f, 0xa8, 0x05, 0xad, 0xa7, 0xc4, 0x5d, 0x4f, 0x56, 0xa7, 0x6e, 0xa3, 0xa7, 0x61, 0xf3, 0x2c,
	0xcf, 0x5b, 0xcd, 0xe7, 0xf2, 0x37, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x9e, 0xc8, 0xdc, 0xab, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SnowflakeClient is the client API for Snowflake service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SnowflakeClient interface {
	Next(ctx context.Context, in *NextRequest, opts ...grpc.CallOption) (*NextReply, error)
	Hello(ctx context.Context, opts ...grpc.CallOption) (Snowflake_HelloClient, error)
	Test(ctx context.Context, opts ...grpc.CallOption) (Snowflake_TestClient, error)
}

type snowflakeClient struct {
	cc *grpc.ClientConn
}

func NewSnowflakeClient(cc *grpc.ClientConn) SnowflakeClient {
	return &snowflakeClient{cc}
}

func (c *snowflakeClient) Next(ctx context.Context, in *NextRequest, opts ...grpc.CallOption) (*NextReply, error) {
	out := new(NextReply)
	err := c.cc.Invoke(ctx, "/snowflake.Snowflake/Next", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snowflakeClient) Hello(ctx context.Context, opts ...grpc.CallOption) (Snowflake_HelloClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Snowflake_serviceDesc.Streams[0], "/snowflake.Snowflake/Hello", opts...)
	if err != nil {
		return nil, err
	}
	x := &snowflakeHelloClient{stream}
	return x, nil
}

type Snowflake_HelloClient interface {
	Send(*StreamReq) error
	Recv() (*StreamResp, error)
	grpc.ClientStream
}

type snowflakeHelloClient struct {
	grpc.ClientStream
}

func (x *snowflakeHelloClient) Send(m *StreamReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *snowflakeHelloClient) Recv() (*StreamResp, error) {
	m := new(StreamResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *snowflakeClient) Test(ctx context.Context, opts ...grpc.CallOption) (Snowflake_TestClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Snowflake_serviceDesc.Streams[1], "/snowflake.Snowflake/Test", opts...)
	if err != nil {
		return nil, err
	}
	x := &snowflakeTestClient{stream}
	return x, nil
}

type Snowflake_TestClient interface {
	Send(*TestReq) error
	Recv() (*TestRes, error)
	grpc.ClientStream
}

type snowflakeTestClient struct {
	grpc.ClientStream
}

func (x *snowflakeTestClient) Send(m *TestReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *snowflakeTestClient) Recv() (*TestRes, error) {
	m := new(TestRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SnowflakeServer is the server API for Snowflake service.
type SnowflakeServer interface {
	Next(context.Context, *NextRequest) (*NextReply, error)
	Hello(Snowflake_HelloServer) error
	Test(Snowflake_TestServer) error
}

// UnimplementedSnowflakeServer can be embedded to have forward compatible implementations.
type UnimplementedSnowflakeServer struct {
}

func (*UnimplementedSnowflakeServer) Next(ctx context.Context, req *NextRequest) (*NextReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Next not implemented")
}
func (*UnimplementedSnowflakeServer) Hello(srv Snowflake_HelloServer) error {
	return status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (*UnimplementedSnowflakeServer) Test(srv Snowflake_TestServer) error {
	return status.Errorf(codes.Unimplemented, "method Test not implemented")
}

func RegisterSnowflakeServer(s *grpc.Server, srv SnowflakeServer) {
	s.RegisterService(&_Snowflake_serviceDesc, srv)
}

func _Snowflake_Next_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnowflakeServer).Next(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/snowflake.Snowflake/Next",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnowflakeServer).Next(ctx, req.(*NextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Snowflake_Hello_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SnowflakeServer).Hello(&snowflakeHelloServer{stream})
}

type Snowflake_HelloServer interface {
	Send(*StreamResp) error
	Recv() (*StreamReq, error)
	grpc.ServerStream
}

type snowflakeHelloServer struct {
	grpc.ServerStream
}

func (x *snowflakeHelloServer) Send(m *StreamResp) error {
	return x.ServerStream.SendMsg(m)
}

func (x *snowflakeHelloServer) Recv() (*StreamReq, error) {
	m := new(StreamReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Snowflake_Test_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SnowflakeServer).Test(&snowflakeTestServer{stream})
}

type Snowflake_TestServer interface {
	Send(*TestRes) error
	Recv() (*TestReq, error)
	grpc.ServerStream
}

type snowflakeTestServer struct {
	grpc.ServerStream
}

func (x *snowflakeTestServer) Send(m *TestRes) error {
	return x.ServerStream.SendMsg(m)
}

func (x *snowflakeTestServer) Recv() (*TestReq, error) {
	m := new(TestReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Snowflake_serviceDesc = grpc.ServiceDesc{
	ServiceName: "snowflake.Snowflake",
	HandlerType: (*SnowflakeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Next",
			Handler:    _Snowflake_Next_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Hello",
			Handler:       _Snowflake_Hello_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Test",
			Handler:       _Snowflake_Test_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "snow.proto",
}
